---
title: "Research Topics"
author: "Team lol - Tamsin Connerly, Hannah Lee, Jasmine Xiang"
format: pdf
execute: 
  warning: false
  message: false
editor: visual
---

1.  A brief description of the topic

2.  A statement about your motivation for investigating this topic

3.  The potential audience(s), i.e., who might be most interested in this research?

4.  Two or three potential research questions you could analyze about this topic. *(Note: These are draft questions at this point. You will finalize the questions in the next stage of the project.)*

5.  Ideas about the type of data you might use to answer this question or potential data sets you’re interested in using. (*Note: The goal is to generate ideas at this point, so it is fine if you have not identified any particular data sets at this point.)*

## Research Topic 1

1.  The MTA in New York City implemented congestion pricing on January 5, 2025 to attempt to decrease rush hour traffic especially in Manhattan and encourage people to use public transportation. The MTA releases data about the effects of congestion pricing (specifically, vehicle traffic at different hours) that we can use to perform some sort of data analysis. (<https://www.mta.info/article/most-detailed-view-of-nyc-traffic-so-far>)
2.  Tamsin is motivated to investigate this topic because she worked at the Department of Transportation last summer and is going to work alongside the MTA next summer trying to figure out how to get people to use more public transportation. The rest of the group is interested in studying climate impact.
3.  The potential audience for this is transportation officials, urban planners, and the general public because the Congestion Pricing is a big headline in the news right now.
4.  Has congestion pricing significantly changed the hours at which vehicles enter Manhattan? Has congestion pricing significantly changed the average type of vehicle entering the congestion zone?
5.  I would use the MTA Open Data platform (linked above).

\pagebreak

## Research Topic 2

1.  Air pollution is a growing concern in urban areas and has implications for public health and quality of life. Air pollution levels may greatly influences housing prices. Research in this could potentially reveal some insights into the cost of environmental degradation. This dataset from kaggle (<https://www.kaggle.com/datasets/epa/epa-historical-air-quality>) contains a vast collection of air quality data collected from ambient air monitoring sites across the country.

2.  Jasmine have taken en environmental data analysis course last semester and learned that urban citizens have been facing significant health risks for a long time bacause of the air pollution. She is wiling to figure out whether real estate prices could reflect people's willingness to pay for cleaner environments.

3.  Environmental economists, real estate developers and agents, and even urban planners and policymakers may be potential audience of this project.

4.  How do varying air pollution levels across neighborhoods affect housing prices? Do wealthier neighborhoods show more resistance to the negative effects of air pollution on property values?

5.  I would use Air quality data linked above.

\pagebreak

## Research Topic 3

1.  Ever since the COVID-19 outbreak, a growing number of adults and children have been experiencing depression and anxiety. Although there are widespread mental health impacts from the pandemic, some people are more likely to be impacted than others, depending on a variety of factors such as mothers, people from different ethnic or racial groups, or healthcare workers. This dataset from Kaggle (<https://www.kaggle.com/datasets/divaniazzahra/mental-health-dataset/data>) contains a variety of different variables that we could look at and perform data analysis.
2.  Hannah is motivated to investigate this topic because she is passionate about mental health and is a volunteer crisis counselor for the national crisis text line. The rest of the group is interested in different variables that might make certain individuals more likely to be impacted.
3.  The potential audience for this is mental health experts who may be interested in any trends in mental health, as well as anyone interested in spreading awareness about mental health and making resources more accessible to vulnerable populations.
4.  Are there specific regions that have more individuals that experience more mental health impacts? What variable has the greatest impact on making individuals more likely to experience mental health impacts?
5.  I would use the dataset linked above.
